import test,{beforeEach,afterEach}from'node:test';import assert from'node:assert/strict';import request from'supertest';import{mkdtempSync,rmSync}from'node:fs';import os from'node:os';import path from'node:path';import crypto from'node:crypto';import{createApp}from'../src/app.js';import{createDatabase}from'../src/db.js';
let db,app,dir,a,b,c,ids,conversationId;const credentials={password:'Password123!',dateOfBirth:'2000-01-01'};
async function register(agent,name,email){await agent.post('/api/auth/register').send({...credentials,fullName:name,email});return db.prepare('SELECT id FROM users WHERE email=?').get(email).id;}
function addMatch(x,y){const[one,two]=x<y?[x,y]:[y,x];db.prepare('INSERT OR IGNORE INTO matches(id,user_one_id,user_two_id,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),one,two,'2026-08-12T10:00:00.000Z');}
beforeEach(async()=>{dir=mkdtempSync(path.join(os.tmpdir(),'chat-test-'));db=createDatabase(':memory:');app=createApp({db,config:{isProduction:false,sessionDays:7,uploadDir:dir,matchMinimumScore:40,matchLimit:20,matchCandidateScanLimit:100,chatMaxMessageLength:20,chatDefaultPageSize:2,chatMaxPageSize:3,chatMessageRateLimit:30},now:()=>new Date('2026-08-12T12:00:00.000Z')});a=request.agent(app);b=request.agent(app);c=request.agent(app);ids={a:await register(a,'Alice','alice@chat.test'),b:await register(b,'Ben','ben@chat.test'),c:await register(c,'Cara','cara@chat.test')};addMatch(ids.a,ids.b);conversationId=(await a.post(`/api/conversations/open/${ids.b}`)).body.conversation.id;});afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
test('both matched participants access the same conversation',async()=>{const ar=await a.get(`/api/conversations/${conversationId}`),br=await b.get(`/api/conversations/${conversationId}`);assert.equal(ar.status,200);assert.equal(br.status,200);assert.equal(ar.body.conversation.id,br.body.conversation.id);assert.equal(ar.body.conversation.participant.id,ids.b);assert.equal(br.body.conversation.participant.id,ids.a);});
test('unmatched user cannot access or send to another conversation',async()=>{assert.equal((await c.get(`/api/conversations/${conversationId}`)).status,404);assert.equal((await c.get(`/api/conversations/${conversationId}/messages`)).status,404);assert.equal((await c.post(`/api/conversations/${conversationId}/messages`).send({message:'intrusion'})).status,404);});
test('pending rejected and cancelled requests do not permit chat',async()=>{for(const status of['pending','rejected','cancelled']){db.prepare('INSERT INTO match_requests(id,sender_user_id,receiver_user_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),ids.a,ids.c,status,'2026-08-12','2026-08-12');assert.equal((await a.post(`/api/conversations/open/${ids.c}`)).status,403);}});
test('changing conversation ID cannot expose another users chat',async()=>{addMatch(ids.b,ids.c);const other=(await b.post(`/api/conversations/open/${ids.c}`)).body.conversation.id;assert.equal((await a.get(`/api/conversations/${other}`)).status,404);assert.equal((await a.post(`/api/conversations/${other}/messages`).send({message:'no'})).status,404);assert.equal((await a.get('/api/conversations/not-real')).status,404);});
test('valid message is session-authored, trimmed, persisted, and retrievable',async()=>{const r=await a.post(`/api/conversations/${conversationId}/messages`).send({message:'  Study at 7?  '});assert.equal(r.status,201);assert.equal(r.body.message.senderUserId,ids.a);assert.equal(r.body.message.message,'Study at 7?');const stored=db.prepare('SELECT * FROM messages WHERE id=?').get(r.body.message.id);assert.equal(stored.sender_user_id,ids.a);assert.equal((await b.get(`/api/conversations/${conversationId}/messages`)).body.messages[0].message,'Study at 7?');});
test('mass assignment and sender impersonation are rejected',async()=>{const r=await a.post(`/api/conversations/${conversationId}/messages`).send({message:'hello',senderUserId:ids.c});assert.equal(r.status,400);assert.equal(db.prepare('SELECT count(*) count FROM messages').get().count,0);});
test('empty whitespace and over-limit messages are rejected',async()=>{for(const message of['','   ','x'.repeat(21)])assert.equal((await a.post(`/api/conversations/${conversationId}/messages`).send({message})).status,400);});
test('message history is newest-first with stable cursor pagination',async()=>{const insert=db.prepare('INSERT INTO messages(id,conversation_id,sender_user_id,message_text,created_at,updated_at) VALUES(?,?,?,?,?,?)');for(let i=1;i<=5;i++){const t=`2026-08-12T12:0${i}:00.000Z`;insert.run(`message-${i}`,conversationId,ids.a,`message ${i}`,t,t);}const first=await a.get(`/api/conversations/${conversationId}/messages`);assert.deepEqual(first.body.messages.map(x=>x.id),['message-5','message-4']);assert.equal(first.body.pagination.hasMore,true);const second=await a.get(`/api/conversations/${conversationId}/messages?cursor=${encodeURIComponent(first.body.pagination.nextCursor)}`);assert.deepEqual(second.body.messages.map(x=>x.id),['message-3','message-2']);const third=await a.get(`/api/conversations/${conversationId}/messages?cursor=${encodeURIComponent(second.body.pagination.nextCursor)}`);assert.deepEqual(third.body.messages.map(x=>x.id),['message-1']);assert.equal(third.body.pagination.hasMore,false);});
test('page size is capped and invalid cursor is rejected',async()=>{const insert=db.prepare('INSERT INTO messages(id,conversation_id,sender_user_id,message_text,created_at,updated_at) VALUES(?,?,?,?,?,?)');for(let i=0;i<5;i++)insert.run(`m${i}`,conversationId,ids.a,'x',`2026-08-12T12:0${i}:00Z`,`2026-08-12T12:0${i}:00Z`);const r=await a.get(`/api/conversations/${conversationId}/messages?limit=99`);assert.equal(r.body.messages.length,3);assert.equal(r.body.pagination.limit,3);assert.equal((await a.get(`/api/conversations/${conversationId}/messages?cursor=broken`)).status,400);});
test('conversation opens only for match and duplicate or concurrent opens are idempotent',async()=>{const again=await b.post(`/api/conversations/open/${ids.a}`);assert.equal(again.body.conversation.id,conversationId);const results=await Promise.all([a.post(`/api/conversations/open/${ids.b}`),b.post(`/api/conversations/open/${ids.a}`)]);assert.ok(results.every(x=>x.status===200));assert.equal(db.prepare('SELECT count(*) count FROM conversations').get().count,1);});
test('self and unmatched conversation opening are forbidden',async()=>{assert.equal((await a.post(`/api/conversations/open/${ids.a}`)).status,400);assert.equal((await a.post(`/api/conversations/open/${ids.c}`)).status,403);});
test('removing accepted match revokes existing conversation access',async()=>{db.prepare('DELETE FROM matches').run();assert.equal((await a.get(`/api/conversations/${conversationId}`)).status,404);assert.equal((await b.post(`/api/conversations/${conversationId}/messages`).send({message:'hello'})).status,404);});
test('conversation list returns only participant conversations and last message',async()=>{await a.post(`/api/conversations/${conversationId}/messages`).send({message:'Review tonight'});addMatch(ids.b,ids.c);await b.post(`/api/conversations/open/${ids.c}`);const list=(await a.get('/api/conversations')).body.conversations;assert.equal(list.length,1);assert.equal(list[0].id,conversationId);assert.equal(list[0].lastMessage.message,'Review tonight');});
test('chat responses expose only public participant fields',async()=>{const responses=[(await a.get(`/api/conversations/${conversationId}`)).body.conversation,(await a.get('/api/conversations')).body.conversations[0]];for(const response of responses){const text=JSON.stringify(response);for(const secret of['email','dateOfBirth','password_hash','passwordHash','sessionToken','accountStatus'])assert.ok(!text.includes(secret));assert.deepEqual(Object.keys(response.participant).sort(),['course','displayName','id','profilePictureUrl','school','yearLevel'].sort());}});
test('all chat routes require authentication',async()=>{assert.equal((await request(app).get('/api/conversations')).status,401);assert.equal((await request(app).post(`/api/conversations/open/${ids.b}`)).status,401);assert.equal((await request(app).get(`/api/conversations/${conversationId}/messages`)).status,401);assert.equal((await request(app).post(`/api/conversations/${conversationId}/messages`).send({message:'x'})).status,401);});
