import test,{beforeEach,afterEach} from 'node:test';import assert from 'node:assert/strict';import request from 'supertest';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {createApp} from '../src/app.js';import {createDatabase} from '../src/db.js';import {calculateCompatibility} from '../src/matching-service.js';
let db,app,dir,a,b,c,ids;const base={password:'Password123!',dateOfBirth:'2000-01-01'};const complete={school:'State University',course:'BSIT',yearLevel:'2nd Year',bio:'Focused learner',preferredStudyMode:'Online',subjectIds:[1,2],goalIds:[1,2],studyStyleIds:[1,2]};
async function register(agent,fullName,email){await agent.post('/api/auth/register').send({...base,fullName,email});return db.prepare('SELECT id FROM users WHERE email=?').get(email).id;}
async function setProfile(agent,name,overrides={}){await agent.put('/api/profile').send({...complete,displayName:name,...overrides});}
beforeEach(async()=>{dir=mkdtempSync(path.join(os.tmpdir(),'match-test-'));db=createDatabase(':memory:');app=createApp({db,config:{isProduction:false,sessionDays:7,uploadDir:dir,matchMinimumScore:40,matchLimit:20,matchCandidateScanLimit:100},now:()=>new Date('2026-08-12T12:00:00Z')});a=request.agent(app);b=request.agent(app);c=request.agent(app);ids={a:await register(a,'Alice','alice@test.com'),b:await register(b,'Ben','ben@test.com'),c:await register(c,'Cara','cara@test.com')};await setProfile(a,'Alice');await setProfile(b,'Ben');await setProfile(c,'Cara',{subjectIds:[3],goalIds:[3],studyStyleIds:[3],preferredStudyMode:'In-person'});});afterEach(()=>{db.close();rmSync(dir,{recursive:true,force:true});});
const schedule=[{day:'Monday',startTime:'19:00',endTime:'21:00'}];
test('authenticated user retrieves ranked matches while unauthenticated access is rejected',async()=>{await a.put('/api/profile/availability').send({availability:schedule});await b.put('/api/profile/availability').send({availability:schedule});const r=await a.get('/api/matches');assert.equal(r.status,200);assert.equal(r.body.matches[0].user.id,ids.b);assert.equal((await request(app).get('/api/matches')).status,401);});
test('self and inactive users are excluded',async()=>{db.prepare("UPDATE users SET account_status='suspended' WHERE id=?").run(ids.b);const r=await a.get('/api/matches');assert.ok(!r.body.matches.some(x=>x.user.id===ids.a));assert.ok(!r.body.matches.some(x=>x.user.id===ids.b));});
test('scoring components increase deterministically and remain bounded',()=>{const empty={subjects:[],studyGoals:[],studyStyles:[],preferredStudyMode:null,availability:[]};const full={subjects:[{id:1}],studyGoals:[{id:1}],studyStyles:[{id:1}],preferredStudyMode:'Online',availability:schedule};const baseline=calculateCompatibility(empty,empty);const subject=calculateCompatibility({...empty,subjects:full.subjects},{...empty,subjects:full.subjects});const goals=calculateCompatibility({...empty,studyGoals:full.studyGoals},{...empty,studyGoals:full.studyGoals});const styles=calculateCompatibility({...empty,studyStyles:full.studyStyles},{...empty,studyStyles:full.studyStyles});const mode=calculateCompatibility({...empty,preferredStudyMode:'Online'},{...empty,preferredStudyMode:'Online'});const availability=calculateCompatibility({...empty,availability:schedule},{...empty,availability:schedule});assert.equal(baseline.score,0);assert.equal(subject.score,35);assert.equal(goals.score,20);assert.equal(styles.score,15);assert.equal(mode.score,10);assert.equal(availability.score,20);for(const result of [baseline,subject,goals,styles,mode,availability,calculateCompatibility(full,full)])assert.ok(result.score>=0&&result.score<=100);});
test('mode scoring follows exact, either, and incompatible rules',()=>{const p=(mode)=>({subjects:[],studyGoals:[],studyStyles:[],availability:[],preferredStudyMode:mode});assert.equal(calculateCompatibility(p('Online'),p('Online')).breakdown.studyMode,10);assert.equal(calculateCompatibility(p('Either'),p('Online')).breakdown.studyMode,5);assert.equal(calculateCompatibility(p('Online'),p('In-person')).breakdown.studyMode,0);});
test('overlapping availability increases compatibility',async()=>{const before=(await a.get('/api/matches')).body.matches.find(x=>x.user.id===ids.b).compatibility.score;await a.put('/api/profile/availability').send({availability:schedule});await b.put('/api/profile/availability').send({availability:schedule});const after=(await a.get('/api/matches')).body.matches.find(x=>x.user.id===ids.b).compatibility;assert.ok(after.score>before);assert.ok(after.reasons.includes('1 overlapping study schedule'));});
test('results are sorted deterministically by score',async()=>{await setProfile(c,'Cara',{subjectIds:[1],goalIds:[1],studyStyleIds:[3],preferredStudyMode:'Either'});const matches=(await a.get('/api/matches')).body.matches;for(let i=1;i<matches.length;i++)assert.ok(matches[i-1].compatibility.score>=matches[i].compatibility.score);});
test('minimum threshold and maximum limit are enforced',async()=>{app=createApp({db,config:{isProduction:false,sessionDays:7,uploadDir:dir,matchMinimumScore:90,matchLimit:1,matchCandidateScanLimit:100},now:()=>new Date('2026-08-12T12:00:00Z')});const login=request.agent(app);await login.post('/api/auth/login').send({email:'alice@test.com',password:base.password});let matches=(await login.get('/api/matches')).body.matches;assert.ok(matches.every(x=>x.compatibility.score>=90));assert.ok(matches.length<=1);});
test('reasons and breakdown reflect actual shared inputs',async()=>{const match=(await a.get('/api/matches')).body.matches.find(x=>x.user.id===ids.b);assert.ok(match.compatibility.reasons.includes('2 shared subjects'));assert.ok(match.compatibility.reasons.includes('2 shared study goals'));assert.ok(match.compatibility.reasons.includes('2 shared study styles'));assert.ok(match.compatibility.reasons.includes('Same study mode'));assert.deepEqual(match.compatibility.breakdown,{subjects:35,goals:20,studyStyles:15,studyMode:10,availability:0});});
test('match responses expose only approved profile fields',async()=>{const match=(await a.get('/api/matches')).body.matches[0];for(const key of ['email','dateOfBirth','password','passwordHash','password_hash','session','sessionToken'])assert.equal(key in match.user,false);});
test('client cannot submit compatibility score',async()=>{const r=await a.post(`/api/matches/${ids.c}/request`).send({score:100});assert.equal(r.status,201);assert.equal('score' in r.body.request,false);});
test('user can send request and duplicate or reverse pending requests are rejected',async()=>{assert.equal((await a.post(`/api/matches/${ids.b}/request`)).status,201);assert.equal((await a.post(`/api/matches/${ids.b}/request`)).status,409);assert.equal((await b.post(`/api/matches/${ids.a}/request`)).status,409);});
test('self-request and invalid or inactive targets are rejected',async()=>{assert.equal((await a.post(`/api/matches/${ids.a}/request`)).status,400);assert.equal((await a.post('/api/matches/missing/request')).status,404);db.prepare("UPDATE users SET account_status='disabled' WHERE id=?").run(ids.c);assert.equal((await a.post(`/api/matches/${ids.c}/request`)).status,404);});
test('receiver accepts and creates exactly one normalized mutual match',async()=>{await a.post(`/api/matches/${ids.b}/request`);assert.equal((await b.post(`/api/matches/${ids.a}/accept`)).status,200);const rows=db.prepare('SELECT * FROM matches').all();assert.equal(rows.length,1);assert.ok(rows[0].user_one_id<rows[0].user_two_id);assert.equal((await b.post(`/api/matches/${ids.a}/accept`)).status,404);assert.equal((await a.post(`/api/matches/${ids.b}/request`)).status,409);assert.throws(()=>db.prepare('INSERT INTO matches(id,user_one_id,user_two_id,created_at) VALUES(?,?,?,?)').run('duplicate',rows[0].user_one_id,rows[0].user_two_id,new Date().toISOString()));assert.throws(()=>db.prepare('INSERT INTO matches(id,user_one_id,user_two_id,created_at) VALUES(?,?,?,?)').run('reverse',rows[0].user_two_id,rows[0].user_one_id,new Date().toISOString()));});
test('receiver can reject and sender can cancel pending requests',async()=>{await a.post(`/api/matches/${ids.b}/request`);assert.equal((await b.post(`/api/matches/${ids.a}/reject`)).body.request.status,'rejected');await a.post(`/api/matches/${ids.c}/request`);assert.equal((await a.post(`/api/matches/${ids.c}/cancel`)).body.request.status,'cancelled');});
test('unauthorized user cannot modify another request or manipulate ownership',async()=>{await a.post(`/api/matches/${ids.b}/request`).send({senderUserId:ids.c});assert.equal((await c.post(`/api/matches/${ids.a}/accept`)).status,404);assert.equal((await c.post(`/api/matches/${ids.b}/cancel`)).status,404);const row=db.prepare("SELECT * FROM match_requests WHERE status='pending'").get();assert.equal(row.sender_user_id,ids.a);assert.equal(row.receiver_user_id,ids.b);});
test('request listing contains only the authenticated user records',async()=>{await a.post(`/api/matches/${ids.b}/request`);await c.post(`/api/matches/${ids.b}/request`);const list=(await a.get('/api/match-requests')).body.requests;assert.equal(list.length,1);assert.ok(list.every(x=>x.senderUserId===ids.a||x.receiverUserId===ids.a));});
