import crypto from 'node:crypto';import{z}from'zod';import{authMiddleware}from'./auth.js';import{areMatched,isBlocked}from'./safety.js';
export function createNotification(db,{userId,type,title,message,entityType=null,entityId=null,now}){db.prepare('INSERT INTO notifications(id,user_id,type,title,message,related_entity_type,related_entity_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),userId,type,title,message,entityType,entityId,now.toISOString());}
const instant=z.string().datetime({offset:true});const sessionSchema=z.object({title:z.string().trim().min(1).max(120),description:z.string().trim().max(1000).nullable(),scheduledStart:instant,scheduledEnd:instant,participantUserIds:z.array(z.string().min(1)).min(1).max(20).refine(x=>new Set(x).size===x.length)}).strict();
const reportSchema=z.object({reportedUserId:z.string().min(1),reason:z.string().trim().min(1).max(100),description:z.string().trim().max(1000).nullable(),conversationId:z.string().min(1).nullable()}).strict();
const sessionJson=(db,row)=>({...row,participants:db.prepare('SELECT p.user_id AS id,pr.display_name AS displayName FROM study_session_participants p JOIN profiles pr ON pr.user_id=p.user_id WHERE p.session_id=? ORDER BY pr.display_name').all(row.id)});
export function registerDay5Routes(app,{db,now}){const auth=authMiddleware(db);
 app.post('/api/users/:userId/block',auth,(req,res)=>{const target=req.params.userId;if(target===req.user.id)return res.status(400).json({error:'You cannot block yourself.'});if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(target))return res.status(404).json({error:'User not found.'});try{db.prepare('INSERT INTO blocked_users(blocker_user_id,blocked_user_id,created_at) VALUES(?,?,?)').run(req.user.id,target,now().toISOString());}catch(e){if(String(e).includes('UNIQUE'))return res.status(409).json({error:'User is already blocked.'});throw e;}res.status(201).json({blockedUserId:target});});
 app.delete('/api/users/:userId/block',auth,(req,res)=>{db.prepare('DELETE FROM blocked_users WHERE blocker_user_id=? AND blocked_user_id=?').run(req.user.id,req.params.userId);res.status(204).end();});
 app.get('/api/blocked-users',auth,(req,res)=>res.json({blockedUsers:db.prepare('SELECT b.blocked_user_id AS id,p.display_name AS displayName,b.created_at AS createdAt FROM blocked_users b JOIN profiles p ON p.user_id=b.blocked_user_id WHERE b.blocker_user_id=? ORDER BY b.created_at DESC').all(req.user.id)}));
 app.post('/api/reports',auth,(req,res)=>{const p=reportSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid report.'});const x=p.data;if(x.reportedUserId===req.user.id)return res.status(400).json({error:'You cannot report yourself.'});if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(x.reportedUserId))return res.status(404).json({error:'User not found.'});if(x.conversationId&&!db.prepare('SELECT 1 FROM conversations WHERE id=? AND ((user_one_id=? AND user_two_id=?) OR (user_one_id=? AND user_two_id=?))').get(x.conversationId,req.user.id,x.reportedUserId,x.reportedUserId,req.user.id))return res.status(400).json({error:'Conversation is not related to this report.'});const id=crypto.randomUUID();db.prepare('INSERT INTO reports(id,reporter_user_id,reported_user_id,reason,description,related_conversation_id,created_at) VALUES(?,?,?,?,?,?,?)').run(id,req.user.id,x.reportedUserId,x.reason,x.description,x.conversationId,now().toISOString());res.status(201).json({report:{id}});});
 app.get('/api/reports',auth,(_req,res)=>res.status(403).json({error:'Reports are restricted moderation records.'}));
 app.post('/api/study-sessions',auth,(req,res)=>{const p=sessionSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid study session.'});const x=p.data,start=new Date(x.scheduledStart),end=new Date(x.scheduledEnd);if(!(end>start)||end-start>1000*60*60*24*7)return res.status(400).json({error:'Invalid session date range.'});for(const id of x.participantUserIds)if(!areMatched(db,req.user.id,id)||isBlocked(db,req.user.id,id))return res.status(403).json({error:'All participants must be unblocked matched study buddies.'});const id=crypto.randomUUID(),stamp=now().toISOString();try{db.exec('BEGIN');db.prepare('INSERT INTO study_sessions(id,creator_user_id,title,description,scheduled_start,scheduled_end,status,created_at,updated_at) VALUES(?,?,?,?,?,?,\'scheduled\',?,?)').run(id,req.user.id,x.title,x.description,start.toISOString(),end.toISOString(),stamp,stamp);const add=db.prepare('INSERT INTO study_session_participants(session_id,user_id,created_at) VALUES(?,?,?)');add.run(id,req.user.id,stamp);for(const userId of x.participantUserIds){add.run(id,userId,stamp);createNotification(db,{userId,type:'session_invitation',title:'Study session invitation',message:`${req.user.full_name} invited you to ${x.title}.`,entityType:'study_session',entityId:id,now:now()});}db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}const row=db.prepare('SELECT id,creator_user_id AS creatorUserId,title,description,scheduled_start AS scheduledStart,scheduled_end AS scheduledEnd,status,created_at AS createdAt,updated_at AS updatedAt FROM study_sessions WHERE id=?').get(id);res.status(201).json({session:sessionJson(db,row)});});
 const authorized=(id,user)=>db.prepare('SELECT s.id,s.creator_user_id AS creatorUserId,s.title,s.description,s.scheduled_start AS scheduledStart,s.scheduled_end AS scheduledEnd,s.status,s.created_at AS createdAt,s.updated_at AS updatedAt FROM study_sessions s JOIN study_session_participants p ON p.session_id=s.id WHERE s.id=? AND p.user_id=?').get(id,user);
 app.get('/api/study-sessions',auth,(req,res)=>{const rows=db.prepare('SELECT s.id,s.creator_user_id AS creatorUserId,s.title,s.description,s.scheduled_start AS scheduledStart,s.scheduled_end AS scheduledEnd,s.status,s.created_at AS createdAt,s.updated_at AS updatedAt FROM study_sessions s JOIN study_session_participants p ON p.session_id=s.id WHERE p.user_id=? ORDER BY s.scheduled_start,s.id').all(req.user.id);res.json({sessions:rows.map(x=>sessionJson(db,x))});});
 app.get('/api/study-sessions/:id',auth,(req,res)=>{const row=authorized(req.params.id,req.user.id);if(!row)return res.status(404).json({error:'Study session not found.'});res.json({session:sessionJson(db,row)});});
 app.post('/api/study-sessions/:id/cancel',auth,(req,res)=>{const row=db.prepare("SELECT * FROM study_sessions WHERE id=? AND creator_user_id=? AND status='scheduled'").get(req.params.id,req.user.id);if(!row)return res.status(404).json({error:'Cancellable study session not found.'});const stamp=now().toISOString();try{db.exec('BEGIN');db.prepare("UPDATE study_sessions SET status='cancelled',updated_at=? WHERE id=?").run(stamp,row.id);for(const p of db.prepare('SELECT user_id FROM study_session_participants WHERE session_id=? AND user_id<>?').all(row.id,req.user.id))createNotification(db,{userId:p.user_id,type:'session_cancelled',title:'Study session cancelled',message:`${row.title} was cancelled.`,entityType:'study_session',entityId:row.id,now:now()});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}res.json({status:'cancelled'});});
 app.get('/api/notifications',auth,(req,res)=>res.json({notifications:db.prepare('SELECT id,type,title,message,related_entity_type AS relatedEntityType,related_entity_id AS relatedEntityId,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC,id').all(req.user.id)}));
 app.post('/api/notifications/:id/read',auth,(req,res)=>{const result=db.prepare('UPDATE notifications SET read_at=COALESCE(read_at,?) WHERE id=? AND user_id=?').run(now().toISOString(),req.params.id,req.user.id);if(!result.changes)return res.status(404).json({error:'Notification not found.'});res.status(204).end();});
 app.post('/api/notifications/read-all',auth,(req,res)=>{db.prepare('UPDATE notifications SET read_at=COALESCE(read_at,?) WHERE user_id=?').run(now().toISOString(),req.user.id);res.status(204).end();});
}
