import crypto from 'node:crypto';
import { authMiddleware } from './auth.js';
import { discoverMatches } from './matching-service.js';

const pair=(a,b)=>a<b?[a,b]:[b,a];
const targetActive=(db,id)=>db.prepare("SELECT 1 FROM users WHERE id=? AND account_status='active'").get(id);
export function registerMatchRoutes(app,{db,config,now}) {
  const auth=authMiddleware(db);
  app.get('/api/matches',auth,(req,res)=>res.json({matches:discoverMatches(db,req.user.id,config),pagination:{limit:config.matchLimit,minimumScore:config.matchMinimumScore}}));
  app.post('/api/matches/:userId/request',auth,(req,res)=>{const target=req.params.userId;if(target===req.user.id)return res.status(400).json({error:'You cannot send a match request to yourself.'});if(!targetActive(db,target))return res.status(404).json({error:'Study buddy not found.'});const [one,two]=pair(req.user.id,target);if(db.prepare('SELECT 1 FROM matches WHERE user_one_id=? AND user_two_id=?').get(one,two))return res.status(409).json({error:'You are already matched study buddies.'});if(db.prepare("SELECT 1 FROM match_requests WHERE status='pending' AND ((sender_user_id=? AND receiver_user_id=?) OR (sender_user_id=? AND receiver_user_id=?))").get(req.user.id,target,target,req.user.id))return res.status(409).json({error:'A pending match request already exists.'});const timestamp=now().toISOString(),id=crypto.randomUUID();db.prepare("INSERT INTO match_requests(id,sender_user_id,receiver_user_id,status,created_at,updated_at) VALUES(?,?,?,'pending',?,?)").run(id,req.user.id,target,timestamp,timestamp);res.status(201).json({request:{id,senderUserId:req.user.id,receiverUserId:target,status:'pending',createdAt:timestamp,updatedAt:timestamp}});});
  const transition=(action)=> (req,res)=>{const other=req.params.userId,receiver=action!=='cancel';const request=receiver?db.prepare("SELECT * FROM match_requests WHERE sender_user_id=? AND receiver_user_id=? AND status='pending' ORDER BY created_at DESC LIMIT 1").get(other,req.user.id):db.prepare("SELECT * FROM match_requests WHERE sender_user_id=? AND receiver_user_id=? AND status='pending' ORDER BY created_at DESC LIMIT 1").get(req.user.id,other);if(!request)return res.status(404).json({error:'Authorized pending match request not found.'});const status=action==='accept'?'accepted':action==='reject'?'rejected':'cancelled',timestamp=now().toISOString();try{db.exec('BEGIN');db.prepare('UPDATE match_requests SET status=?,updated_at=? WHERE id=?').run(status,timestamp,request.id);if(status==='accepted'){const [one,two]=pair(request.sender_user_id,request.receiver_user_id);db.prepare('INSERT OR IGNORE INTO matches(id,user_one_id,user_two_id,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),one,two,timestamp);}db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}res.json({request:{id:request.id,senderUserId:request.sender_user_id,receiverUserId:request.receiver_user_id,status,createdAt:request.created_at,updatedAt:timestamp}});};
  app.post('/api/matches/:userId/accept',auth,transition('accept'));app.post('/api/matches/:userId/reject',auth,transition('reject'));app.post('/api/matches/:userId/cancel',auth,transition('cancel'));
  app.get('/api/match-requests',auth,(req,res)=>{const requests=db.prepare(`SELECT id,sender_user_id AS senderUserId,receiver_user_id AS receiverUserId,status,created_at AS createdAt,updated_at AS updatedAt FROM match_requests WHERE sender_user_id=? OR receiver_user_id=? ORDER BY created_at DESC,id`).all(req.user.id,req.user.id);const matches=db.prepare('SELECT id,user_one_id AS userOneId,user_two_id AS userTwoId,created_at AS createdAt FROM matches WHERE user_one_id=? OR user_two_id=? ORDER BY created_at DESC').all(req.user.id,req.user.id);res.json({requests,matches});});
}
